# Generated by Django 4.2.11 on 2025-09-06 10:11

import arbre_genealogique.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('liste_prenoms', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_famille', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=arbre_genealogique.models.image_upload_path)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_couple_avec', to='arbre_genealogique.membre')),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_mere', to='arbre_genealogique.membre')),
                ('pere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_pere', to='arbre_genealogique.membre')),
            ],
        ),
    ]
